### ISSUE TITLE
RFC: Required changes before GA

### ISSUE THREAD

**Issue by mrgrain** [projen/projen#2976]
**Work in Progress: PLEASE COMMENT WITH YOUR VIEWS**

Projen is in major version zero `0.x` and has been for over three years now. It's time for projen to grow up!

In order to do this responsibly, I believe a few things must still be implemented. Starting this list as an RFC today, to gauge community and maintainer priorities. Once accepted, this list will hopefully also help to focus contributions on the remaining tasks:

The list is categorized in two groups. The must haves are defined as the essential tasks needed completion before we consider moving to GA. The nice to haves should be considered high priority tasks, with their implementation status to be assessed once we are ready for GA. However they would not be blocking a GA release.

## Must have
- [ ] Define & document a release and versioning strategy for past GA aka how to deal with future breaking changes (Ideas: stick with semver or adopt a schedule like Node.js)
- [ ] Use Constructs #2974 #1671
- [ ] Base framework for interactive prompts #2975
- [ ] Remove hard dependency on GitHub (allow use of other CI/CD tooling) #1761 #1883
- [ ] New Docs page #2340

# Nice to have

- [ ] Full implementation of RFC #1365 including feature selection #2926
- [ ] GitLab support for all built-in workflows (see hard dependency on GitHub) #2438
- [ ] Support custom task runtimes #2468 
- [ ] Full fledged feature injection support (tbd, basically taking what we need for Workflow Engines and TaskRunners and turn it onto a generic system)
- [ ] https://github.com/projen/projen/issues/2042

**Comment by hoegertn** [comment]
I agree on the must-have parts besides the prompt thing. I see the value but not the need for GA.

Happy to help as I would love to have a 1.x to get out of the current version hell.

**Comment by mrgrain** [comment]
> I think stabilizing the task interface should be in the must-have category, as this is a major blocker for integration with other task runners: #2051

Thanks for calling this out. I'll try to phrase this better. In my mind "Change task runner to use dependsOn, rather than imperative instructions" is framed about making projen's task runner better.
While "Support custom task runtimes" is what #2051 is and this will include the task dependencies model as well as caching.

**Comment by mbonig** [comment]
We (Defiance Digital) are working on a new docs site in a fork. It uses Docusaurus and we're hoping to have something presentable by the EOM (Oct 31st).

**Comment by moltar** [comment]
@mbonig +1 on Docusaurus. Although I feel like `mkdocs` will still win because that's what AWS teams seem to have settled at, judging by the use of it across several projects now.

**Comment by mbonig** [comment]
> @mbonig +1 on Docusaurus. Although I feel like `mkdocs` will still win because that's what AWS teams seem to have settled at, judging by the use of it across several projects now.

The main driver on Docusaurus vs mkdocs was the typescript vs python. Projen devs are going to already be doing typescript work and having the docs platform also be js/ts seemed like a better fit than asking any maintainers to have to also know python. Yes, most docs work will just be markdown content, but in the case where it's not, I liked the synergy of having js/ts in Docusaurus.

**Comment by mrpackethead** [comment]
> @mbonig +1 on Docusaurus. Although I feel like `mkdocs` will still win because that's what AWS teams seem to have settled at, judging by the use of it across several projects now.

I don't think that the two pizza teams at AWS take into consideration too much about 'company wide' standards.  They seem to do, what suits their particular team best. 

The must have list is pretty good, though I'm inclined to agree with Thorsten about the CLI, and would have probalby put it in  'nice to have'. 

Using Constructs will be a game changer.

**Comment by moltar** [comment]
> > @mbonig +1 on Docusaurus. Although I feel like `mkdocs` will still win because that's what AWS teams seem to have settled at, judging by the use of it across several projects now.
> 
> The main driver on Docusaurus vs mkdocs was the typescript vs python. Projen devs are going to already be doing typescript work and having the docs platform also be js/ts seemed like a better fit than asking any maintainers to have to also know python. Yes, most docs work will just be markdown content, but in the case where it's not, I liked the synergy of having js/ts in Docusaurus.

Yeah, I am in full alignment on the py vs ts issue. I do prefer Docusaurus too! There are also a couple of plugins for TypeDoc support too, with full theme support.

**Comment by moltar** [comment]
@mrgrain Another suggestion for v1, and I am not sure if there's an issue for it, could be export clean up. This would probably break a lot, unless a backward-compat and, perhaps, a warning is provided.

Right now projen exports everything from `lib/` but ideally root barrel should export everything, and optionally some high-level additional paths, a-la cdk.

**Comment by mrgrain** [comment]
> Right now projen exports everything from `lib/` but ideally root barrel should export everything, and optionally some high-level additional paths, a-la cdk.

Could you open an issue for this and include an example? I'm not sure I 100% understand what you mean.

**Comment by mbonig** [comment]
> > > @mbonig +1 on Docusaurus. Although I feel like `mkdocs` will still win because that's what AWS teams seem to have settled at, judging by the use of it across several projects now.
> > 
> > 
> > The main driver on Docusaurus vs mkdocs was the typescript vs python. Projen devs are going to already be doing typescript work and having the docs platform also be js/ts seemed like a better fit than asking any maintainers to have to also know python. Yes, most docs work will just be markdown content, but in the case where it's not, I liked the synergy of having js/ts in Docusaurus.
> 
> Yeah, I am in full alignment on the py vs ts issue. I do prefer Docusaurus too! There are also a couple of plugins for TypeDoc support too, with full theme support.

One issue that we're having is that Docusaurus can't parse and render the API.md that projen generates. Docusaurus uses MDX and MDX can't parse the current API.md file and fails at some `{}`. I can get more details, but we'll have to work through those problems first.

**Comment by agdimech** [comment]
Looks good although don't think the interactive prompts CLI is mandatory for release. I think we also should add this to the must have category:

- **Standardised interface for configuration:** Some constructs have certain properties that can be set at construction time whilst others only support certain configuration via methods and some use a combination of both. We should ensure all 1st party components follow a standardised format (and document it!) to prevent users from having to actually read the projen code to figure out how to change a certain setting. My preference is to favour methods to change behaviours and use constructors as a quick way to "inject" new components i.e: constructor of a project would have some mechanism to enable/disable/inject components whilst a `getEsLint()` would return the component with a bunch of methods to change settings.

One thing that could fall under _nice to have_ is IDE support for .projenrc. Would be cool to have autocomplete for dependencies similar to package.json to make the experience a little more user friendly.

**Comment by mrgrain** [comment]
> One issue that we're having is that Docusaurus can't parse and render the API.md that projen generates. Docusaurus uses MDX and MDX can't parse the current API.md file and fails at some {}. I can get more details, but we'll have to work through those problems first.

I'm not familiar with MDX, so not quite sure what's going on there. I also have a in progress PR to upgrade the version of jsii-docgen in here. But also feel free to open an issue in jsii-docgen about the incorrectly (?) generated files.

**Comment by mrgrain** [comment]
> Standardised interface for configuration

Would you mind opening a new issue for this, so we can discuss the ins and out there. In principle agree with being consistent, but it feels very vague at the moment.

**Comment by kaizencc** [comment]
My $0.02:

`Framework for interactive prompts in CLI` and `New documentation page` should be in the `Nice to Have` section based on the fact that implementing them would not likely result in any breaking change.

Curious why `Break up projen into several packages` is a `Nice to Have` given that it seems like it would be a breaking change if we decided to go down that path.

The biggest task and highest risk thing is migrating projen to the constructs framework and the impact of that one feature dwarfs the other [important] tasks on the list. It almost feels like that should be where the attention is directed at first, and then we can think about GA'ing what we have after.

**Comment by mrgrain** [comment]
Thanks, @kaizencc 

> Curious why `Break up projen into several packages` is a `Nice to Have` given that it seems like it would be a breaking change if we decided to go down that path.

Good point. This is based on the assumption that projen will release new major versions with breaking changes on a somewhat regular cadence. See the first entry in the list. To me once every year is the upper boundary. In practise, this would mean these changes can still be made, they just might have to wait for a bit even when implemented.

> The biggest task and highest risk thing is migrating projen to the constructs framework and the impact of that one feature dwarfs the other [important] tasks on the list. It almost feels like that should be where the attention is directed at first, and then we can think about GA'ing what we have after.

I have a Draft PR ready for this. Seems relative straightforward to be honest. Impact is mitigated by using Magic AutoIDs. We can do this in projen because here Construct IDs don't mean anything.

**Comment by ahammond** [comment]
Our argument for using projen is that it makes a multi-repo approach viable. One of the main gaps we have right now is compliance across hundreds of repos. I think github-settings is the solution for that, but https://github.com/projen/projen/pull/2987 is a long way from done. I think that's absolutely a Nice to Have, but probably not a Must.

**Comment by tinovyatkin** [comment]
I would add a big wish here - make it possible to use `projen new --from` with non-JSII / non-NPM packages.
For example it completely bombs / limits adoption of projen use in the Python world - I would expect being able to do `pipx projen new --from=some-module-published-to-pypi` from Python world, but I have to write TypeScript and publish it to NPM (crossing to another world).

We do workaround by using `npx projen new from --from=git://repo/repo.git` and manually creating some fake `.jsii` file and little `jsii-bridge.js` + `package.json` inside our repo, but it's not an experience I would recommend to anyone.

Contrary to AWS, many projen projects targeting some specific OS / languages and so JSII doesn't makes any sense for it (if I want to have a template that bootstraps some pythonic project and provides some example - crafting that in Typescript only limits my choices without bringing any benefits to non-Python consumers).

So, having an optional fallback to allow building non-JSII project template would unlock many users creativity.

**Comment by mrgrain** [comment]
> I would add a big wish here - make it possible to use projen new --from with non-JSII / non-NPM packages.
For example it completely bombs / limits adoption of projen use in the Python world - I would expect being able to do pipx projen new --from=some-module-published-to-pypi from Python world, but I have to write TypeScript and publish it to NPM (crossing to another world).

I understand the need. The main challenge is that we currently use `.jsii` for introspection. So what we need is either a completely new introspection engine, or tooling that can create "fake" `.jsii` files for non TS packages. And on top of that we need to implement language specific project generation, but that's easily done I think (just a bit of work). I'm not against this (heck I'm all for it!), but I don't see it happening in the near future.

**Comment by mbonig** [comment]
> > One issue that we're having is that Docusaurus can't parse and render the API.md that projen generates. Docusaurus uses MDX and MDX can't parse the current API.md file and fails at some {}. I can get more details, but we'll have to work through those problems first.
> 
> I'm not familiar with MDX, so not quite sure what's going on there. I also have a in progress PR to upgrade the version of jsii-docgen in here. But also feel free to open an issue in jsii-docgen about the incorrectly (?) generated files.


The problem occurs while MDX is trying to parse this line:

```html
<li parentName="ul"><strong parentName="li">{`command`}</strong>{` (`}<code>{`Array`}<string></code>{`)  Provide a command to the docker container. `}<strong parentName="li"><em parentName="strong">{`Default`}</em></strong>{`: use the container's default command`}</li>
```

With the error:

```
Module build failed (from ./node_modules/@docusaurus/mdx-loader/lib/index.js):
SyntaxError: /Users/matthewbonig/.../projen/docusaurus/docs/API.md: Expected corresponding JSX closing tag for <string>. (2195:93)
```

and the corresponding rendered markdown:

![image](https://github.com/projen/projen/assets/1559437/a9ee0e22-a51c-47a6-a86a-e74f69232de6)

**Comment by mbonig** [comment]
> > > One issue that we're having is that Docusaurus can't parse and render the API.md that projen generates. Docusaurus uses MDX and MDX can't parse the current API.md file and fails at some {}. I can get more details, but we'll have to work through those problems first.
> > 
> > 
> > I'm not familiar with MDX, so not quite sure what's going on there. I also have a in progress PR to upgrade the version of jsii-docgen in here. But also feel free to open an issue in jsii-docgen about the incorrectly (?) generated files.
> 
> The problem occurs while MDX is trying to parse this line:
> 
> ```
> <li parentName="ul"><strong parentName="li">{`command`}</strong>{` (`}<code>{`Array`}<string></code>{`)  Provide a command to the docker container. `}<strong parentName="li"><em parentName="strong">{`Default`}</em></strong>{`: use the container's default command`}</li>
> ```
> 
> With the error:
> 
> ```
> Module build failed (from ./node_modules/@docusaurus/mdx-loader/lib/index.js):
> SyntaxError: /Users/matthewbonig/.../projen/docusaurus/docs/API.md: Expected corresponding JSX closing tag for <string>. (2195:93)
> ```
> 
> and the corresponding rendered markdown:
> 
> ![image](https://user-images.githubusercontent.com/1559437/278194932-a9ee0e22-a51c-47a6-a86a-e74f69232de6.png)

Ok, ignore this. I upgraded to the latest version of docusaurus and they support CommonMark now instead of having to use MDX so this is no longer an issue.

**Comment by mrgrain** [comment]
> Ok, ignore this. I upgraded to the latest version of docusaurus and they support CommonMark now instead of having to use MDX so this is no longer an issue.

This reminds me the projen is using a very old version of jsii-docgen and I need to upgrade that 🙈

**Comment by mrgrain** [comment]
Hey everyone, quick update. I have "finalize" the list based on everyone's feedback. However this is going to be a living document and we can still make changes. However they should be more considered from now on.

Here is the full list of updates:
- Renamed `Nice to Have` to `Should Have` to better convey the intention of items being a high priority for the project, but ultimately releasing GA is more important than having any of the items included.
- Moved `Framework for interactive prompts in CLI` to SHOULD based on feedback
- Removed `Full implementation of RFC: Project creation prompts` completely, since this has too many dependencies on other SHOULD items
- Added new item `Code cleanup tasks` to MUST, encompassing various deprecation and code-reorganization tasks. I expect this list to grow. However I also expect these tasks to mostly happen as part of the cut-over to 1.0, i.e. just before the first GA beta is released
- Extended item `Feature & Configuration injection system` in SHOULD, based on feedback. This is in SHOULD because there are no concrete, accepted solutions at the moment. For projen and the Constructs Programming Model (CPM) the current generally accepted approach is that everything needs to be configurable via constructor properties, with methods providing additional supporting features. We can document this better (and start enforcing it better) irregardless of GA.

**Comment by mrgrain** [comment]
Some notes on not included/changed items:
- "Change task runner to use dependsOn, rather than imperative instructions"
Not MUST, because I don't think it comes up often enough compared to other items.
- "IDE support for .projenrc"
I really hope this can be solved by the community first and then maybe adopted into the org as a separate repo. As it stands I don't think this can be properly supported by maintainers.
- "github-settings"
This would be awesome, but it very much feels like a stand-alone component to me. Which is great, because we can just release it anytime as soon as it's implemented. I ended up not putting it in SHOULD, because its third-party app.
- "make it possible to use projen new --from with non-JSII / non-NPM packages."
This is super interesting, but ultimately requires such a radical departure from the current approach that projen is a jsii package. I'd love to be wrong on this and have a simple solution emerge. Until then, it's just below the cut.

**Comment by rehanvdm** [comment]
> I think stabilizing the task interface should be in the must-have category, as this is a major blocker for integration with other task runners: #2051
> 
> You touch on one of those items in the "Change task runner to use dependsOn, rather than imperative instructions" item.
> 
> But I think there's another very common partner that is similar across many of these task runners that try to optimize for cache leverage: **ability to specify inputs and outputs**. And this needs to happen _per command_, not per task (or both).
> 
> Using Turborepo in the example, but it is the same pattern across all the tools I've seen:
> 
>     * https://turbo.build/repo/docs/reference/configuration#inputs
> 
>     * https://turbo.build/repo/docs/reference/configuration#outputs

I would really not like to see turborepo, nx, lerna in projen. I have used https://github.com/google/wireit in a few projects and it is magical, does just what it is supposed to without the heavily opinionated monorepo things.

**Comment by mrgrain** [comment]
> I would really not like to see turborepo, nx, lerna in projen. I have used https://github.com/google/wireit in a few projects and it is magical, does just what it is supposed to without the heavily opinionated monorepo things.

I am quite sure that non of them will end up directly in projen or even as a default task runtime. IMHO these tools are attracting way too many opinions to endorse a default one  🙊 (proof: this thread)

What projen needs to do is:
a) Adopt a task dependency model that is more inline with modern task runners
b) Adopt an interface for i/o to enable caching
c) Allow task runners to be swapped out at will

**Comment by moltar** [comment]
I think another useful bit of the related functionality here, perhaps, would be to isolate projen task runner from projen synthesizer. Because now, in CI and other envs, the entire projen project needs to be installed just to run the initial task. I think we should have a compact CLI that just does the runner bit, and can be installed super fast from NPM as a single bundled `index.js` file.

**Comment by mrgrain** [comment]
> I think another useful bit of the related functionality here, perhaps, would be to isolate projen task runner from projen synthesizer. Because now, in CI and other envs, the entire projen project needs to be installed just to run the initial task. I think we should have a compact CLI that just does the runner bit, and can be installed super fast from NPM as a single bundled `index.js` file.

Yeah I'm in favour of this, I'm not not entirely sure how to slice the pie correctly.

The projen package currently does three things:
- a standard library (ignoring the task runner for a second, you don't actually need anything else to use projen)
- a task run time that is using `task.json`
- `projen new`


I _think_ we can't split the the latter two from a UX perspective. However I also still want to publish a `create-projen` package as alternative. In that world, you could use `create-projen` to init a new project type that uses a different task runner and you'd never have to use the projen cli.

The other thing to consider is that I'd the projen CLI to either be native or at least bundle node.

**Comment by moltar** [comment]
I think overall, it sounds like a decoupling into programmatic API as one package, and then a CLI that uses said API as another package. And then also rip out the task runner from both of those into yet another package.

**Comment by thoroc** [comment]
> Feature & Configuration injection system

Would that mean that `Component` would be registrable to other `Component` or event to `Project` types?

**Comment by mrgrain** [comment]
> @mrgrain is there an open issue for this one? I and @Pagebakers have thought about this one a lot, including various esoteric approaches, such as using reactive components (using various React stores) and multi-layered synth. This can be a head-banger.

No issue yet. I'd love to hear your thoughts. We have a lot of ideas around this problem, it's similar in CDK land. I have a doc that I need to re-write with other construct libraries in mind (aka projen). I don't think your approaches are that esoteric. We also landed on a reactive engine.

> Would that mean that `Component` would be registrable to other `Component` or event to `Project` types?

It's more about the current abstractions being closed and defining dependencies on interfaces.

Let's imagine you have a `TypeScriptProject`.
You want this project to use either `githubActions` or `bitbucketPipelines` but never both.
Neither option is better or worse, they are just different.

Currently you have to write something like, which isn't too bad really.
```ts
const project = new TypeScriptProject({
  github: false, // diable the default
  bitbucket: true,
  bitbucketOptions: { /* ... */ },
});
```
But it prevents you from using either of those features on a `PythonProject` - unless someone goes an implements it.

If we encapsulate components strictly, we can probably get away with just not having options on the project:
```ts
const project = new TypeScriptProject();
new BitbucketPipelines(project, { /* ... */ });
```

But we have features like the build system that depend on a workflows engine. Somehow that part needs to be able to define it's dependency on either `GitHubActions` or better yet a generic `IWorkflowsEngine`. It could definitely implement defaults and create themselves, but really what it should be able to do the following with project acting as an [IoC container](https://martinfowler.com/articles/injection.html):

```ts
const workflows = project.get("IWorkflowsEngine");
```

That leads to the question of how users would register their workflow engine, and in extension how (opinionated) library authors can register defaults ("we use Bitbucket at this company, so `IWorkflowsEngine` should be `BitbucketPipelines` unless specified otherwise").

One way (there are many) to achieve this, could be layering features onto Constructs from the outside. It's a bit like traits or mixins, so I like to call this concept Construct Traits:

```ts
// This could be a way to register a default for something
any('IWorkflowsEngine').of(Project).defaultsTo(BitbucketPipelines);

// construct traits are injected from the outside
const myProject = new TypeScriptProject()
  .with(bitbucketPipelines({ /* ... */ }));
// or without fluent interface
bitbucketPipelines(myProject, { /* ... */ });

// they can also be applied to the construct tree (similar to aspects):
any(isGithubWorkflow).of(myProject).uses(setMyRunnerGroups);
```

But a challenge with all of these solutions is what @moltar alluded to: They tend to strongly depend on a certain engine implementation, or at least a common interface. Which is something that doesn't exists in the CMP at the moment. But it could, or it could also just live in projen.

**Comment by thoroc** [comment]
Ok I get what you mean.

I was just looking for clarification as I was playing around in the past few months with a projen type that would allow users to define an object as a generic property on options passed to the project as a specific type from available ones (as `Enum`) AND provide a mean to define tasks that would plug into that component depending on user choices.  Hence my interest in seeing that being decoupled.

As for having a common interface to tie up any implementation, it seems a pretty standard thing.

**Comment by mbonig** [comment]
@mrgrain Right now the API.md file that is generated is quite large. Is there any option to break that up easily into smaller files?

**Comment by mrgrain** [comment]
> @mrgrain Right now the API.md file that is generated is quite large. Is there any option to break that up easily into smaller files?

Yes. There's a flag in jsii-docgen to split by submodule.

I also kind of want to split by language and submodule, but that's not properly working right now.

**Comment by mbonig** [comment]
> > @mrgrain Right now the API.md file that is generated is quite large. Is there any option to break that up easily into smaller files?
> 
> Yes. There's a flag in jsii-docgen to split by submodule.
> 
> I also kind of want to split by language and submodule, but that's not properly working right now.

I can include the splitting in our PR if you can point me to how to do that.

Also, how is the current site being deployed so I can start to plan workflows for changing it to handle the new docusaurus site?

**Comment by mrgrain** [comment]
> I can include the splitting in our PR if you can point me to how to do that.

It's the `--submodule` flag. We probably need to introduce this as an optional option to the docgen component.
https://github.com/cdklabs/jsii-docgen?tab=readme-ov-file#cli-options

> Also, how is the current site being deployed so I can start to plan workflows for changing it to handle the new docusaurus site?

There is an option to use GitHub Actions instead. That's probably the future and we can definitely enable that.

<img width="804" alt="image" src="https://github.com/projen/projen/assets/379814/7c6c800c-0296-4f35-adb1-b1b16173c9db">

**Comment by mbonig** [comment]
> > I can include the splitting in our PR if you can point me to how to do that.
> 
> It's the `--split-by-submodule` flag. We probably need to introduce this as an optional option to the docgen component. https://github.com/cdklabs/jsii-docgen?tab=readme-ov-file#cli-options
>

Tried this and it doesn't appear to do anything. Could it be that projen doesn't have any 'submodules' per jsii?

` npx jsii-docgen -o docusaurus/docs/api/API.md --split-by-submodule`

produces only one API.md file. Not providing a filename and only providing a path results in an error.

**Comment by mrgrain** [comment]
Works on main. You can check the `.jsii` assembly if your version still has submodules. Might be related to the other issue you run into?
<img width="409" alt="image" src="https://github.com/projen/projen/assets/379814/c702f5e2-19b1-45a9-859e-e3de7f69334b">
<img width="490" alt="image" src="https://github.com/projen/projen/assets/379814/980b4ea7-7b96-4c88-a79f-66e09f868e44">

**Comment by mbonig** [comment]
> Works on main. You can check the `.jsii` assembly if your version still has submodules. Might be related to the other issue you run into? <img alt="image" width="409" src="https://user-images.githubusercontent.com/379814/282937183-c702f5e2-19b1-45a9-859e-e3de7f69334b.png"> <img alt="image" width="490" src="https://user-images.githubusercontent.com/379814/282937222-980b4ea7-7b96-4c88-a79f-66e09f868e44.png">

What was the full command you ran to get that?

**Comment by agdimech** [comment]
@mbonig - out of curiosity, are you planning to build a new `DocusaurusComponent/DocusaurusProject` which Projen will dogfood to create its own docs site?

Reason I ask is that I was planning on building a MkDocs or Docusaurus Project myself but if this is already in the works I can just wait and/or contribute if there is a public branch available.

**Comment by mbonig** [comment]
> @mbonig - out of curiosity, are you planning to build a new `DocusaurusComponent/DocusaurusProject` which Projen will dogfood to create its own docs site?
> 
> Reason I ask is that I was planning on building a MkDocs or Docusaurus Project myself but if this is already in the works I can just wait and/or contribute if there is a public branch available.

I did not. I thought about it, and would like to get there, but the focus was on the docs, and I didn't want to take longer than needed (this has already been almost a 6 month effort, tbh) to get this out.

**Comment by mbonig** [comment]
> > I can include the splitting in our PR if you can point me to how to do that.
> 
> It's the `--split-by-submodule` flag. We probably need to introduce this as an optional option to the docgen component. https://github.com/cdklabs/jsii-docgen?tab=readme-ov-file#cli-options
> 

One thing I just discovered about this... it creates nice files for the submodules, but no documentation for the projen (root) module itself. Any ideas on how to fix this? I've opened an issue with jsii-docgen too... (https://github.com/cdklabs/jsii-docgen/issues/1240)

**Comment by mrgrain** [comment]
> > > I can include the splitting in our PR if you can point me to how to do that.
> > 
> > 
> > It's the `--split-by-submodule` flag. We probably need to introduce this as an optional option to the docgen component. https://github.com/cdklabs/jsii-docgen?tab=readme-ov-file#cli-options
> 
> One thing I just discovered about this... it creates nice files for the submodules, but no documentation for the projen (root) module itself. Any ideas on how to fix this? I've opened an issue with jsii-docgen too... ([cdklabs/jsii-docgen#1240](https://github.com/cdklabs/jsii-docgen/issues/1240))

This is fixed now. `jsii-docgen -o docs/api/API.md --split-by-submodule` works for me  now.

**Comment by hoegertn** [comment]
Is there any idea how we can proceed here?

0.x version lead to a lot of version hell and I would love to have a projen GA

**Comment by mrgrain** [comment]
There are three open tasks and two of these can definitely be progressed already.

- **Release & Versioning Strategy** I've said I'd pick this up, but haven't made any progress yet. Could do with some help.
- https://github.com/projen/projen/issues/1761 Needs someone to own this.
- **Code cleanup tasks** probably can't do all of them just yet, but I'd be okay to accept PRs that start to remove deprecations.

**Comment by moltar** [comment]
> Release & Versioning Strategy I've said I'd pick this up, but haven't made any progress yet. Could do with some help.

Been enjoying working with changesets as of late. Seems like the most straightforward magic-less release workflow thus far from all of the ones I've tried.

**Comment by mrgrain** [comment]
> > Release & Versioning Strategy I've said I'd pick this up, but haven't made any progress yet. Could do with some help.
> 
> Been enjoying working with changesets as of late. Seems like the most straightforward magic-less release workflow thus far from all of the ones I've tried.

Sorry, this task is about the "What" not the "How". We need something like this: https://github.com/nodejs/Release

**Comment by gmeligio** [comment]
> Windows support, amongst others

Hi. Do you think the initial work on Windows support is enough to mark this Windows task as done? In terms of ownership, can it be put into the community? I can volunteer for some tasks in my free time because I use projen in Windows and Linux, but I don't know the owner's responsibilities in general.

**Comment by loganfarr** [comment]
Hi @mrgrain 
With the recent sets of breaking changes, I wanted to ask about the latest status about projen going to GA/v1 since this issue hasn't been updated in a while. 

Latest description & update from 2024:
> There are three open tasks and two of these can definitely be progressed already.
>
> * **Release & Versioning Strategy** I've said I'd pick this up, but haven't made any progress yet. Could do with some help.
> 
> * [Decouple `Project` from GitHub #1761](https://github.com/projen/projen/issues/1761) Needs someone to own this.
> 
> * **Code cleanup tasks** probably can't do all of them just yet, but I'd be okay to accept PRs that start to remove the oldest deprecations.

Is this still the case or are there other things that you are tracking for projen GA? 
(I am also willing to help where it's needed, if there's a good issue to start with.)

Thank you for the work you do for the projen project!

**Comment by mrgrain** [comment]
These tasks are all still open except that we have removed most deprecations recently. 

But this was all 2024 and our leadership has changed a few times since then. Once we all feel ready for GA, I'll have to bring this up again internally to see where we are at. I wouldn't hold my breath for GA, it's not going to happen tomorrow.
